before_install: 
  - "mysql -e 'CREATE DATABASE TodoList;'"
dist: xenial
language: php
os: 
  - linux
php: 
  - "7.4"
script: 
  - "composer install"
  - "composer prepare"
  - vendor/bin/phpunit
services: 
  - mysql

env:
  global:
    - DB_NAME=TodoList
    - DB_USER=travis
    - DB_PASSWORD=
