"language": "php",
"os": [
  "linux"
],
"dist": "xenial",
"php": [
  "7.4"
],
"services": [
  "mysql"
],
"before_install": [
  "mysql -e 'CREATE DATABASE TodoList;'"
],
"script": [
  "composer install",
  "composer prepare",
  "vendor/bin/phpunit"
]
