before_install: 
  - "mysql -e 'CREATE DATABASE TodoList;'"
dist: xenial
language: php
os: 
  - linux
php: 
  - "7.4"
install:
    - composer install --prefer-dist --no-interaction --dev
    - php bin/console doctrine:database:create --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load -n --env=test
services: 
  - mysql
script:
    - phpunit tests/ --coverage-text --colors 
